name: Continuous Deployment (AWS-EC2)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Give permission to gradlew
        run: chmod +x gradlew
      - name: Build Project
        run:  ./gradlew clean bootJar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run:  docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }} .
      - name: Publish image to Dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

  deploy:
    needs:  build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from Dockerhub
        run:  sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
      - name: Delete old container
        run:  docker rm -f ${{ secrets.DOCKER_CONTAINER_NAME }}
      - name: Run docker container
        run: docker run -d -p 80:8080 --name ${{ secrets.DOCKER_CONTAINER_NAME }} --restart unless-stopped ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest